apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: application-secrets
  namespace: application-namespace
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: awssecretstore          #secretstore reference in the namespace
    kind: SecretStore
  target:
    name: secrets-application
    creationPolicy: Owner
  data:
  - secretKey: A_PASSWORD
    remoteRef:
      key: "sandbox/application"     # aws secret key
      property: a_password
  - secretKey: B_PASSWORD
    remoteRef:
      key: "sandbox/application"
      property: b_password
