name: LTS Build Dev Trial Containers
on:
  push: 
    branches:
      - trial
  workflow_dispatch:

jobs:
  build-and-publish-dev-qa:
    uses: LTS/ga-reusable-workflows/.github/workflows/BuildTrial.yml@main
    secrets: inherit
