name: LTS Build Final Production Container

on:
  push:
    tags:
      - '*'

jobs:
  publish-prod-container:
    uses: LTS/ga-reusable-workflows/.github/workflows/BuildProd.yml@main
    secrets: inherit
