apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: application-secrets
  namespace: application-namespace
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: awssecretstore          #secretstore reference in the namespace
    kind: SecretStore
  target:
    name: secrets-application
    creationPolicy: Owner
  data:
  - secretKey: A_PASSWORD
    remoteRef:
      key: "sandbox/application"     # aws secret key
      property: a_password
  - secretKey: B_PASSWORD
    remoteRef:
      key: "sandbox/application"
      property: b_password
---
#this is an example of putting secrets INTO files like config files
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: application-externalsecrets
  namespace: application-namespace
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: awssecretstore
    kind: SecretStore
  dataFrom:
    - extract:
        key: "dev/application-secrets"
  target:
    name: secrets-application-config-rendered
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            items:
              - key: sample_file.py
              - key: sample_file2.rb
            name: application-templates-cm
