apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: awssecretstore            #name of secret store
spec:
  provider:
    aws:
      service: SecretsManager
      # Define a specific role to limit access
      #arn:aws:iam::217428790895:user/huit-srv-account-dev-nrs-sa
      #Add the user account ID after the aws:iam annotation
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secret
            key: access-key           # DO NOT CHANGE
          secretAccessKeySecretRef:
            name: aws-secret
            key: secret-access-key    # DO NOT CHANGE
